### ISSUE TITLE
override val scalaCheckInitialSeed = ... leads to NullPointerException

### ISSUE THREAD

**Issue by FrancescoSerra** [scalameta/munit#563]
Hi, as per the output in [this issue](https://github.com/http4s/http4s/issues/6538), I've been overriding the scalaCheckInitialSeed, but when running the test I got:
```
==> X org.http4s.PathSuite.initializationError  0.002s java.lang.NullPointerException: Cannot invoke "String.length()" because "s$1" is null
    at org.scalacheck.rng.Seed$.$anonfun$fromBase64$1(Seed.scala:188)
    at scala.util.Try$.apply(Try.scala:210)
    at org.scalacheck.rng.Seed$.fromBase64(Seed.scala:187)
    at munit.ScalaCheckEffectSuite.$anonfun$initialSeed$1(ScalaCheckEffectSuite.scala:42)
    at scala.Option.getOrElse(Option.scala:201)
    at munit.ScalaCheckEffectSuite.$init$(ScalaCheckEffectSuite.scala:42)

```
However, `override **def** scalaCheckInitialSeed =` worked just fine.

**Comment by armanbilge** [comment]
`lazy val` can probably work here too. But honestly a `def` seems fine for a `String` constant.
