### ISSUE TITLE
`ExceptionInInitializerError` causes test to hang for entire timeout

### ISSUE THREAD

**Issue by armanbilge** [scalameta/munit#772]
```scala
//> using dep org.scalameta::munit::1.0.0-M12

import munit.FunSuite
import scala.concurrent.Future
import scala.concurrent.ExecutionContext

object Dep {
  def attr: Boolean = true

  throw new IllegalArgumentException("boom")
}

final class InitSuite extends FunSuite {
  test("hanging") {
    Future(assert(Dep.attr))(ExecutionContext.global)
  }
}
```

```
java.lang.ExceptionInInitializerError
        at InitSuite.$init$$$anonfun$1$$anonfun$1$$anonfun$1(foo.test.scala:15)
        at munit.Assertions.munitCaptureClues(Assertions.scala:299)
        at munit.Assertions.munitCaptureClues$(Assertions.scala:15)
        at munit.FunSuite.munitCaptureClues(FunSuite.scala:11)
        at munit.Assertions.assert$$anonfun$1(Assertions.scala:30)
        at munit.Assertions.assert$$anonfun$adapted$1(Assertions.scala:34)
        at munit.internal.console.StackTraces$.dropInside(StackTraces.scala:10)
        at munit.Assertions.assert(Assertions.scala:34)
        at munit.Assertions.assert$(Assertions.scala:15)
        at munit.FunSuite.assert(FunSuite.scala:11)
        at InitSuite.$init$$$anonfun$1$$anonfun$1(foo.test.scala:15)
        at InitSuite.$init$$$anonfun$1$$anonfun$adapted$1(foo.test.scala:15)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalArgumentException: boom
        at Dep$.<clinit>(foo.test.scala:10)
        ... 20 more
InitSuite:
==> X InitSuite.hanging  30.01s java.util.concurrent.TimeoutException: test timed out after 30 seconds
```

h/t @milessabin

**Comment by armanbilge** [comment]
Might be related to this.

https://github.com/scalameta/munit/blob/83cb747ff13b4f9bad00b0dff94ef1ef12096f2b/munit/shared/src/main/scala/munit/Exceptions.scala#L11-L20

**Comment by milessabin** [comment]
I think the issue is here,
https://github.com/scalameta/munit/blob/83cb747ff13b4f9bad00b0dff94ef1ef12096f2b/munit/jvm/src/main/scala/munit/internal/PlatformCompat.scala#L73-L80
The `ExceptionInInitializerError` will escape the `Try` and so the timeout won't be cancelled.

**Comment by armanbilge** [comment]
@kitbellew huh, that's interesting. I can still repro with 1.0.4. Are you using scala-cli or maybe some other way of running the test?

**Comment by kitbellew** [comment]
> [@kitbellew](https://github.com/kitbellew) huh, that's interesting. I can still repro with 1.0.4. Are you using scala-cli or maybe some other way of running the test?

I added this test as a suite to this repository and ran `sbt testsJVM/test`.

**Comment by kitbellew** [comment]
ok, turns out i was putting `object Dep` within the test (where it doesn't fail) and not at the file level (where it does).

so, here's the result: if you use `munitExecutionContext`, everything works. even if it's set to `ExecutionContext.global` at the test suite level.

however, if you `ExecutionContext.global` in your future only, I found no way to catch the exception, it's just not propagated anywhere.

[here](https://github.com/scala/scala/blob/2.13.x/src/library/scala/concurrent/impl/Promise.scala#L441) the exception is looked at but since it's not `NonFatal`, not handled.

so... i give up.

**Comment by milessabin** [comment]
I think this is a situation where `NonFatal` isn't the right choice, which in turn means that `Try` isn't the right thing to use here.
